// LOGIN
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/* LOGOUT */
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// REGISTER
export const ADD_USER = "ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILURE = "ADD_USER_FAILURE"

// FORGOT
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

// FORGOT
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"

//RUTIN
export const INPUT_RUTIN = "INPUT_RUTIN"
export const INPUT_RUTIN_SUCCESS = "INPUT_RUTIN_SUCCESS"
export const INPUT_RUTIN_FAILURE = "INPUT_RUTIN_FAILURE"

// BANNER
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILURE = "GET_BANNER_FAILURE";

// DONASILIST
export const GET_DONASI = "GET_DONASI";
export const GET_DONASI_SUCCESS = "GET_DONASI_SUCCESS";
export const GET_DONASI_FAILURE = "GET_DONASI_FAILURE";

// DONASILIST 2
export const GET_DONASI2 = "GET_DONASI2";
export const GET_DONASI2_SUCCESS = "GET_DONASI2_SUCCESS";
export const GET_DONASI2_FAILURE = "GET_DONASI2_FAILURE";

// PAGE DONASI
export const GET_PAGEDONASI = "GET_PAGEDONASI";
export const GET_PAGEDONASI_SUCCESS = "GET_PAGEDONASI_SUCCESS";
export const GET_PAGEDONASI_FAILURE = "GET_PAGEDONASI_FAILURE";

// PAGE DONASI 2
export const GET_PAGEDONASI2 = "GET_PAGEDONASI2";
export const GET_PAGEDONASI2_SUCCESS = "GET_PAGEDONASI2_SUCCESS";
export const GET_PAGEDONASI2_FAILURE = "GET_PAGEDONASI2_FAILURE";

/* TOKEN */
export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

/* DETAIL_DONASI */
export const GET_DETAIL_DONASI = "GET_DETAIL_DONASI";
export const GET_DETAIL_DONASI_SUCCESS = "GET_DETAIL_DONASI_SUCCESS";
export const GET_DETAIL_DONASI_FAILURE = "GET_DETAIL_DONASI_FAILURE";

/* DETAIL_DONASI */
export const GET_DETAIL_DONASI_RUTIN = "GET_DETAIL_DONASI_RUTIN";
export const GET_DETAIL_DONASI_RUTIN_SUCCESS = "GET_DETAIL_DONASI_RUTIN_SUCCESS";
export const GET_DETAIL_DONASI_RUTIN_FAILURE = "GET_DETAIL_DONASI_RUTIN_FAILURE";


// ORDER
export const ORDER = "ORDER";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";
export const ORDER_RUTIN = "ORDER_RUTIN";
export const ORDER_RUTIN_SUCCESS = "ORDER_RUTIN_SUCCESS";
export const ORDER_RUTIN_FAILURE = "ORDER_RUTIN_FAILURE";

// HISTORY 
export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";
// CONFIRM
export const ADD_CONFIRM = "ADD_CONFIRM"
export const ADD_CONFIRM_SUCCESS = "ADD_CONFIRM_SUCCESS"
export const ADD_CONFIRM_FAILURE = "ADD_CONFIRM_FAILURE"

// DETAIL
export const GET_DETAIL = "GET_DETAIL";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAILURE = "GET_DETAIL_FAILURE";
export const GET_DONATION_DETAIL_SUCCESS = "GET_DONATION_DETAIL_SUCCESS";
export const GET_DONATION_DETAIL_FAILURE = "GET_DONATION_DETAIL_FAILURE";
export const GET_CONFIRMLIST = "GET_CONFIRMLIST";
export const GET_CONFIRMLIST_SUCCESS = "GET_CONFIRMLIST_SUCCESS";
export const GET_CONFIRMLIST_FAILURE = "GET_CONFIRMLIST_FAILURE";

// INVOICE
export const INVOICE = "INVOICE";
export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_FAILURE = "INVOICE_FAILURE";

// HISTORY DONATION
export const GET_HISTORY_DONATION = "GET_HISTORY_DONATION";
export const GET_HISTORY_DONATION_SUCCESS = "GET_HISTORY_DONATION_SUCCESS";
export const GET_HISTORY_DONATION_FAILURE = "GET_HISTORY_DONATION_FAILURE";

// ALL HISTORY DONATION
export const GET_ALL_HISTORY_DONATION = "GET_ALL_HISTORY_DONATION";
export const GET_ALL_HISTORY_DONATION_SUCCESS = "GET_ALL_HISTORY_DONATION_SUCCESS";
export const GET_ALL_HISTORY_DONATION_FAILURE = "GET_ALL_HISTORY_DONATION_FAILURE";

// PAGE PAKET DONASI 2
export const GET_PAKET_PAGEDONASI2 = "GET_PAKET_PAGEDONASI2";
export const GET_PAKET_PAGEDONASI2_SUCCESS = "GET_PAKET_PAGEDONASI2_SUCCESS";
export const GET_PAKET_PAGEDONASI2_FAILURE = "GET_PAKET_PAGEDONASI2_FAILURE";

/* DETAIL_DONASI PAKET */
export const GET_DETAIL_PAKET_DONASI_RUTIN = "GET_DETAIL_PAKET_DONASI_RUTIN";
export const GET_DETAIL_PAKET_DONASI_RUTIN_SUCCESS = "GET_DETAIL_PAKET_DONASI_RUTIN_SUCCESS";
export const GET_DETAIL_PAKET_DONASI_RUTIN_FAILURE = "GET_DETAIL_PAKET_DONASI_RUTIN_FAILURE";

// ALL HISTORY DONATION RUTIN
export const GET_ALL_PAKET_RUTIN_HISTORY_DONATION = "GET_ALL_PAKET_RUTIN_HISTORY_DONATION";
export const GET_ALL_PAKET_RUTIN_HISTORY_DONATION_SUCCESS = "GET_ALL_PAKET_RUTIN_HISTORY_DONATION_SUCCESS";
export const GET_ALL_PAKET_RUTIN_HISTORY_DONATION_FAILURE = "GET_ALL_PAKET_RUTIN_HISTORY_DONATION_FAILURE";

// HISTORY DONATION RUTIN
export const GET_PAKET_RUTIN_HISTORY_DONATION = "GET_PAKET_RUTIN_HISTORY_DONATION";
export const GET_PAKET_RUTIN_HISTORY_DONATION_SUCCESS = "GET_PAKET_RUTIN_HISTORY_DONATION_SUCCESS";
export const GET_PAKET_RUTIN_HISTORY_DONATION_FAILURE = "GET_PAKET_RUTIN_HISTORY_DONATION_FAILURE";